name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # se ejecuta todos los días a la medianoche
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate the snake
        uses: Platane/snk@v3
        with:
          github_user_name: BallesterosDev56
          outputs: |
            ./output/github-contribution-grid-snake.svg
          color_snake: '#00FF00'           
          color_dots: '#444,#c6e48b,#7bc96f,#239a3b,#196127' 

      - name: Commit and Push
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "Generate snake contribution grid"
